version: "3.9"
services:
  prod-backend:
    depends_on:
      - db
    restart: always
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    links:
      - db

  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
